using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;
using System.Threading;

namespace Waypoint.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class DialogResultGenerator : IIncrementalGenerator
{
    private const string AttributeNamespace = "Waypoint";
    private const string AttributeName = "DialogResultAttribute";
    internal const string FullyQualifiedAttributeName = $"{AttributeNamespace}.{AttributeName}";
    private const string EmbeddedAttributeSource = """
                // <auto-generated/>
                namespace Microsoft.CodeAnalysis
                {
                    internal sealed partial class EmbeddedAttribute : global::System.Attribute
                    {
                    }
                }
                """;
    private const string DialogResultAttributeSource = $$"""
                // <auto-generated/>
                using System;
                namespace {{AttributeNamespace}}
                {
                    /// <summary>
                    /// Applied to an event in a ViewModel class to instruct the source generator to
                    /// produce the <c>IDialogView&lt;TResult&gt;</c> boilerplate on the paired View.
                    /// </summary>
                    /// <param name="viewType">
                    /// The View type for which the <c>IDialogView&lt;TResult&gt;</c> partial class
                    /// will be generated. The View must be declared as <c>partial</c> and
                    /// inherit the <c>Avalonia.StyledElement</c> base class.
                    /// </param>
                    [Microsoft.CodeAnalysis.Embedded]
                    [AttributeUsage(AttributeTargets.Event, Inherited = false, AllowMultiple = false)]
                    internal sealed class {{AttributeName}} : Attribute
                    {
                        public Type ViewType { get; }
                        public {{AttributeName}}(Type viewType)
                        {
                            ViewType = viewType;
                        }
                    }
                }
                """;

    // Entry point for source generator
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {

        // 1. Output the marker attribute into the user's compilation
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("Microsoft.CodeAnalysis.EmbeddedAttribute.g.cs", SourceText.From(EmbeddedAttributeSource, Encoding.UTF8));
            ctx.AddSource($"{AttributeName}.g.cs", SourceText.From(DialogResultAttributeSource, Encoding.UTF8));
        });

        // 2. Create the pipeline to find attributed events and extract the necessary information into a model
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: FullyQualifiedAttributeName,
                predicate: static (node, _) => node is EventDeclarationSyntax or VariableDeclaratorSyntax,
                transform: GetModel)
            .Where(static m => m is not null);

        // 3. Register the source output
        context.RegisterSourceOutput(provider, GenerateCode);
    }

    // Extract the necessary information from the attributed event
    private static DialogResultModel? GetModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        // Must be an event
        if (ctx.TargetSymbol is not IEventSymbol eventSymbol)
            return null;

        // Must be accessible from the generated view
        if (eventSymbol.DeclaredAccessibility < Accessibility.Internal)
            return null;

        // Must be a delegate that returns void and has exactly one parameter
        if (!Helper.IsActionEventSignature(eventSymbol, out var resultType) || resultType is null)
            return null;

        ct.ThrowIfCancellationRequested();

        // TViewModel must be a non-generic type
        var viewModelType = eventSymbol.ContainingType;
        if (viewModelType.IsGenericType)
            return null;

        // Extract the TView type from the attribute's constructor arguments
        // ForAttributeWithMetadataName guarantees ctx.Attributes contains only the target attribute
        if (!Helper.GetViewType(ctx.Attributes[0], out var viewType) || viewType is null)
            return null;

        // TView must be a non-generic type
        if (viewType.IsGenericType)
            return null;

        // TView must inherit from Avalonia.StyledElement
        if (!Helper.IsStyledElement(viewType))
            return null;

        // Return a value-equatable model
        return new DialogResultModel(
            viewNamespace: viewType.ContainingNamespace.IsGlobalNamespace ? "" : viewType.ContainingNamespace.ToDisplayString(),
            viewName: viewType.Name,
            viewModelName: viewModelType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            eventName: eventSymbol.Name,
            isStatic: eventSymbol.IsStatic,
            resultTypeName: resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
        );
    }

    // Generate the source code for the partial class implementing IDialogView<TResult>
    private static void GenerateCode(SourceProductionContext ctx, DialogResultModel? model)
    {
        if (model is null) return;

        var namespaceDeclaration = string.IsNullOrEmpty(model.ViewNamespace)
            ? ""
            : $"namespace {model.ViewNamespace};";

        var dataContextPattern = model.IsStatic
            ? model.ViewModelName
            : $"{model.ViewModelName} vm";

        var vmEvent = model.IsStatic
            ? $"{model.ViewModelName}.{model.EventName}"
            : $"vm.{model.EventName}";

        var source = $$"""
                // <auto-generated/>
                #nullable enable
                using System;
                using Avalonia;
                using Avalonia.Controls;
                using Avalonia.LogicalTree;
                using Waypoint;

                {{namespaceDeclaration}}

                partial class {{model.ViewName}} : IDialogView<{{model.ResultTypeName}}>
                {
                    public event Action<{{model.ResultTypeName}}>? CloseRequested;

                    protected override void OnAttachedToLogicalTree(LogicalTreeAttachmentEventArgs e)
                    {
                        base.OnAttachedToLogicalTree(e);

                        if (DataContext is {{dataContextPattern}})
                            {{vmEvent}} += OnCloseRequested;
                    }

                    protected override void OnDetachedFromLogicalTree(LogicalTreeAttachmentEventArgs e)
                    {
                        if (DataContext is {{dataContextPattern}})
                            {{vmEvent}} -= OnCloseRequested;

                        base.OnDetachedFromLogicalTree(e);
                    }

                    private void OnCloseRequested({{model.ResultTypeName}} result)
                        => CloseRequested?.Invoke(result);
                }
                """;

        ctx.AddSource($"{model.ViewName}.IDialogView.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    // Value-equatable model ensures generator avoids duplicate work on unchanged items
    private record DialogResultModel
    {
        public string ViewNamespace { get; }
        public string ViewName { get; }
        public string ViewModelName { get; }
        public string EventName { get; }
        public bool IsStatic { get; }
        public string ResultTypeName { get; }

        public DialogResultModel(string viewNamespace, string viewName, string viewModelName, string eventName, bool isStatic, string resultTypeName)
        {
            ViewNamespace = viewNamespace;
            ViewName = viewName;
            ViewModelName = viewModelName;
            EventName = eventName;
            IsStatic = isStatic;
            ResultTypeName = resultTypeName;
        }
    }
}